// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"github.com/project-flogo/core/data/expression/script/gocc/token"
)

const (
	NoState    = -1
	NumStates  = 77
	NumSymbols = 82
)

type Lexer struct {
	src    []byte
	pos    int
	line   int
	column int
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:    src,
		pos:    0,
		line:   1,
		column: 1,
	}
	return lexer
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	return NewLexer(src), nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = new(token.Token)
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '0'
1: '.'
2: '.'
3: '$'
4: '.'
5: '.'
6: '|'
7: '|'
8: '&'
9: '&'
10: '='
11: '='
12: '!'
13: '='
14: '<'
15: '<'
16: '='
17: '>'
18: '>'
19: '='
20: '+'
21: '-'
22: '*'
23: '/'
24: '%'
25: '!'
26: '('
27: ')'
28: '?'
29: ':'
30: 't'
31: 'r'
32: 'u'
33: 'e'
34: 'f'
35: 'a'
36: 'l'
37: 's'
38: 'e'
39: 'n'
40: 'i'
41: 'l'
42: 'n'
43: 'u'
44: 'l'
45: 'l'
46: '['
47: ']'
48: ','
49: '_'
50: 'e'
51: 'E'
52: '+'
53: '-'
54: '\'
55: 'n'
56: '\'
57: 'r'
58: '\'
59: 't'
60: '"'
61: '\'
62: '"'
63: '"'
64: '''
65: '\'
66: '''
67: '''
68: '`'
69: '`'
70: '_'
71: ' '
72: '\t'
73: '\v'
74: '\f'
75: '\r'
76: '\n'
77: '1'-'9'
78: 'a'-'z'
79: 'A'-'Z'
80: '0'-'9'
81: .
*/
